### ISSUE TITLE
POST may not be working correctly with Content-Type: application/json (Error: Insert failed, duplicate id)

### ISSUE THREAD

**Issue by smaglio81** [typicode/jsonplaceholder#62]
**Expected Behavior**

As outlined here: https://github.com/typicode/jsonplaceholder#creating-a-resource

I was expecting the result to be a `200 OK` with an object with these properties:
```
/* will return
{
  id: 101,
  title: 'foo',
  body: 'bar',
  userId: 1
}
*/
```

**Actual Behavior**

A response of `500 Internal Server Error` and a body of:
```
Error: Insert failed, duplicate id
    at Function.insert (/app/node_modules/lodash-id/src/index.js:49:18)
    at /app/node_modules/lodash/lodash.js:4379:28
    at arrayReduce (/app/node_modules/lodash/lodash.js:704:21)
    at baseWrapperValue (/app/node_modules/lodash/lodash.js:4378:14)
    at LodashWrapper.wrapperValue (/app/node_modules/lodash/lodash.js:9067:14)
    at create (/app/node_modules/json-server/lib/server/router/plural.js:223:50)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:137:13)
    at next (/app/node_modules/express/lib/router/route.js:131:14)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
```

**Reproduction**

Using PostMan ...

  **`POST`** to `http://jsonplaceholder.typicode.com/posts/`

Headers
`Content-Type: application/json; charset=UTF-8`

Body
```
{
	"userId": 1,
	"id": 1,
	"title": "sunt aut",
	"body": "quia et"
}
```

**Additional Reproduction Information**

You can reproduce the error as long as the `Content-Type` has `application/json` within it. If you remove that value it will not return a `500 Internal Server Error`, instead it will return a `200 Ok` but with an unexpected data object.

**Doesn't Work (returns `500`)**
`Content-Type: application/json; charset=UTF-8`
`Content-Type: application/json`

**Does Work (returns `200`, but with an unexpected data object)**
`Content-Type: charset=UTF-8`
`Content-Type: text/xml`
`no Content-Type header`

Unexpected data object:
```
{
    "id": 101
}
```

**Comment by nicolidin** [comment]
I have the same isssue, any news about it ?
